# common.
UNIQUE_ID_KEY = "_id"

# lecture_instances collection.
INSTANCES_COLLECTION_LECTURE_ID_KEY = "lecture_id"
INSTANCES_COLLECTION_SPACE_ID_KEY = "space_id"
INSTANCES_COLLECTION_DATE_KEY = "date"
INSTANCES_COLLECTION_TAGS_KEY = "tags"

# lectures collection.
LECTURES_COLLECTION_USERNAME_KEY = "username"
LECTURES_COLLECTION_TITLE_KEY = "title"
LECTURES_COLLECTION_DESCRIPTION_KEY = "description"
LECTURES_COLLECTION_RATING_KEY = "rating"
LECTURES_COLLECTION_TAGS_KEY = "tags"
LECTURES_COLLECTION_CATEGORY_KEY = "category"
LECTURES_COLLECTION_COMMENTS_KEY = "comments"

# spaces collection.
SPACES_COLLECTION_NAME_KEY = "name"
SPACES_COLLECTION_USERS_KEY = "users"

# tags collection.
TAGS_COLLECTION_NAME_KEY = "tag_name"
TAGS_COLLECTION_LAST_USAGE_KEY = "last_usage"

# users collection.
USERS_COLLECTION_USERNAME_KEY = "username"
USERS_COLLECTION_DISPLAY_NAME_KEY = "display_name"
USERS_COLLECTION_CONTACT_DETAILS_KEY = "contact_details"
USERS_COLLECTION_AVAILABILITY_KEY = "availability"
USERS_COLLECTION_AVAILABILITY_HOURS_KEY = "hours"
USERS_COLLECTION_AVAILABILITY_DAYS_KEY = "days"
USERS_COLLECTION_TAGS_KEY = "tags"
